[pytest]
addopts = --import-mode=importlib -q
testpaths =
    01-dft-fundamentals-qe/tests
    02-dft-vacancy-diffusion-creep/tests
    03-creep-data-analysis/tests
    04-deformation-mechanism-maps/tests
    05-ml-creep-rupture-life/tests
    06-ml-hea-phase-strength/tests
    07-sps-joule-heating-densification/tests
    08-phase-field-sintering/tests
    09-md-nanocrystalline-creep/tests
    10-dft-al-creep-parameters/tests
    11-ideal-shear-strength-ogata2002/tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
