"""Physically consistent SYNTHETIC creep curves.

These are NOT experimental data. They exist so that every analysis step can be tested
against known "true" parameters before it is applied to real lab data, and so the
repository runs end-to-end without confidential results.

Model for a test at stress sigma and temperature T:

    eps_dot_ss = A * ((sigma - sigma_th(T)) / E(T))^n * exp(-Q / RT)       minimum rate
    t_r        = C_MG / eps_dot_ss^m  (log-normal scatter)                  Monkman-Grant
    eps(t)     = eps0 + th1 (1 - exp(-th2 t)) + eps_dot_ss t + th3 (exp(th4 t) - 1)

with the primary (th1, th2) and tertiary (th3, th4) terms scaled to t_r so the curve
looks like a real constant-load test, then sampled like a data logger and given
extensometer noise.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .curves import CreepTest

R = 8.314462618


@dataclass
class SyntheticAlloy:
    name: str = "DemoAlloy-SP (synthetic, single phase)"
    A: float = 3.0e22  # 1/s, pre-factor of the (sigma/E)^n form
    n: float = 4.5
    Q_kJ: float = 290.0
    E_RT_GPa: float = 210.0
    dEdT_GPa_per_K: float = -0.07
    sigma_th_RT_MPa: float = 0.0  # threshold stress at 293 K (0 = none)
    sigma_th_dT: float = 0.0  # MPa/K decrease of threshold with temperature
    C_MG: float = 0.08  # Monkman-Grant constant (strain units)
    m_MG: float = 0.92
    eps_fracture: float = 0.18
    primary_strain: float = 0.012
    eps_elastic_plus_loading: float = 0.002
    scatter_log10_tr: float = 0.08
    noise_strain: float = 2e-5

    def E(self, T_K):
        return self.E_RT_GPa + self.dEdT_GPa_per_K * (np.asarray(T_K) - 293.0)

    def sigma_th(self, T_K):
        return max(self.sigma_th_RT_MPa - self.sigma_th_dT * (T_K - 293.0), 0.0)

    def min_rate(self, stress_MPa, T_K):
        s_eff = max(stress_MPa - self.sigma_th(T_K), 1e-6)
        return self.A * (s_eff / (1000.0 * self.E(T_K))) ** self.n * np.exp(-self.Q_kJ * 1000.0 / (R * T_K))


#: A particle/composite-strengthened variant: apparent n is large because of sigma_th.
COMPOSITE = SyntheticAlloy(
    name="DemoAlloy-C (synthetic, composite with threshold stress)",
    A=2.0e23, n=4.4, Q_kJ=300.0, sigma_th_RT_MPa=95.0, sigma_th_dT=0.085,
    eps_fracture=0.10, primary_strain=0.006,
)


def creep_curve(alloy: SyntheticAlloy, stress_MPa: float, T_C: float, rng=None,
                n_points: int = 600, specimen_id: str = "") -> CreepTest:
    rng = rng or np.random.default_rng()
    T = T_C + 273.15
    rate = alloy.min_rate(stress_MPa, T)  # 1/s
    t_r = alloy.C_MG / rate**alloy.m_MG * 10 ** rng.normal(0.0, alloy.scatter_log10_tr)  # s

    th1 = alloy.primary_strain * rng.uniform(0.8, 1.2)
    th2 = 25.0 / t_r  # primary decays within ~10% of life
    th4 = 7.0 / t_r
    eps0 = alloy.eps_elastic_plus_loading
    remaining = alloy.eps_fracture * rng.uniform(0.85, 1.15) - eps0 - th1 - rate * t_r
    th3 = max(remaining, 0.2 * alloy.eps_fracture) / (np.exp(th4 * t_r) - 1.0)

    t = np.linspace(0.0, t_r, n_points)
    eps = eps0 + th1 * (1 - np.exp(-th2 * t)) + rate * t + th3 * (np.exp(th4 * t) - 1)
    eps = eps + rng.normal(0.0, alloy.noise_strain, size=t.size)
    eps[0] = eps0
    return CreepTest(
        time_h=t / 3600.0, strain=eps, stress_MPa=stress_MPa, temperature_C=T_C,
        specimen_id=specimen_id, ruptured=True,
        metadata={"source": "SYNTHETIC - generated by creepkit.synthetic", "alloy": alloy.name,
                  "true_min_rate_per_s": float(rate), "true_n": alloy.n, "true_Q_kJ": alloy.Q_kJ,
                  "true_sigma_th_MPa": float(alloy.sigma_th(T))},
    )


#: Default test matrix: (temperature in C, list of stresses in MPa)
TEST_MATRIX = {
    600: [220, 260, 300, 340],
    650: [160, 190, 220, 260],
    700: [110, 130, 160, 190],
    750: [80, 95, 110, 130],
}

COMPOSITE_MATRIX = {
    600: [130, 150, 175, 210, 250],
    650: [130, 150, 175, 210, 250],
    700: [110, 130, 155, 185, 220],
    750: [95, 110, 130, 160, 195],
}


def generate_dataset(alloy: SyntheticAlloy, matrix=TEST_MATRIX, seed: int = 42):
    rng = np.random.default_rng(seed)
    tests = []
    for T_C, stresses in matrix.items():
        for s in stresses:
            tests.append(creep_curve(alloy, s, T_C, rng, specimen_id=f"T{T_C}_S{s}"))
    return tests
